### ISSUE TITLE
Exception not re-raised in catchall except block

### ISSUE THREAD

**Issue by simongarnier** [trustpilot/python-lambdarest#26]
I discovered that `create_lambda_handler()` decorator is [catching](https://github.com/trustpilot/python-lambdarest/blob/master/lambdarest/__init__.py#L139) any exception thrown by the handler, logging the error and then returning a 500 response. 

Usually when catching all exception, one would re-raise the exception so it would bubble up and code registering the handler could do something useful with the exception. In my case, I want to capture such exception using a decorator provided by the sentry SDK(raven) to get visibility on errors in my code.

Your solution works great in the case where you get your stack trace in cloud watch or something but is not very flexible if you want to get them outside of your cloud provider.

I'm curious about your opinion, I've already made the required change and associated test in a branch on my fork.

**Comment by sloev** [comment]
Lambdarest was made with our stack in focus, we use Cloudwatch and therefore i chose to `catch and log` instead of elevating exceptions since that would lay off responsibility of replies to Amazon Api Gateway. In general i wanted as much control in my lambda as possible.

But that could be solved by using the pattern `flask`and `connexion` is using (if i remember correctly) of specifying the errorhandler during initialization of `lambda_handler`.

We could: 
```
lambda_handler = create_lambda_handler(error_handler=None)
```
Here `lambda_handler` would raise all errors.

What do you think?

**Comment by simongarnier** [comment]
Great idea! If I understand correctly, the `create_lambda_handler()` function would have a default `error_handler` to replicates the behavior of the old exception handling. If set to `None`, we would just raise the exception.

I implemented this [here](https://github.com/trustpilot/python-lambdarest/pull/27).

**Comment by sloev** [comment]
Awesome, exactly! and i find the solution just as i would have written it. Great work!
I have some feedback (relayed from review of PR):
Can you: 
bump the version number in __init__.py and setup.py to 2.2.6 and write an entry in HISTORY about the change ?

kind regards 
Johannes Valbjorn

**Comment by sloev** [comment]
thanks, i should have created some guidelines mentioning the manual version stuff.

Merged

**Comment by jacksgt** [comment]
Hi, there I had the same problem and just stumbled across this issue. I agree with the default behavior, because it makes it very easy to get started. However, I think this behavior is worth mentioning in the README, since I had to spend quite some time to figure our why my `except` block was not being executed.
 I will contribute a PR in the next few days.
